#!/usr/bin/env bash
# Write .cursor/auto-context.md for session handoff (tier B). Safe to run often.
set -euo pipefail

ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
cd "$ROOT"
OUT=".cursor/auto-context.md"
mkdir -p .cursor

{
  echo "# Auto context"
  echo ""
  echo "> Generated by \`scripts/refresh-auto-context.sh\` — do not edit. Regenerated on file edits and stop hook."
  echo ""
  echo "**Updated (UTC):** $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo ""
  echo "## Git"
  echo "- **Branch:** $(git branch --show-current 2>/dev/null || echo '(detached/none)')"
  echo "- **HEAD:** $(git rev-parse --short HEAD 2>/dev/null || echo '(no commits)')"
  echo ""
  echo "### Status"
  echo '```'
  git status -sb 2>/dev/null || echo '(not a git repo)'
  echo '```'
  echo ""
  echo "### Recent commits"
  echo '```'
  git log -8 --oneline 2>/dev/null || true
  echo '```'
  echo ""
  echo "### Diff stat"
  echo '```'
  git diff --stat 2>/dev/null || true
  git diff --cached --stat 2>/dev/null || true
  echo '```'
  echo ""
  if [[ -f .cursor/data-model.json ]]; then
    echo "## Data model (excerpt)"
    echo '```json'
    python3 -c "import json; d=json.load(open('.cursor/data-model.json')); print(json.dumps({k:d.get(k) for k in ('status','summary','entities')}, indent=2))" 2>/dev/null || head -15 .cursor/data-model.json
    echo '```'
    echo ""
  fi
  if [[ -f .cursor/implementation-notes.md ]]; then
    echo "## Implementation notes (excerpt)"
    echo '```'
    head -40 .cursor/implementation-notes.md
    echo '```'
    echo ""
  fi
  echo "## Untracked (sample)"
  echo '```'
  git ls-files --others --exclude-standard 2>/dev/null | head -20 || true
  echo '```'
} >"$OUT"
